export const browserCoreExamples = [
  "vilaro browser status",
  "vilaro browser start",
  "vilaro browser stop",
  "vilaro browser tabs",
  "vilaro browser open https://example.com",
  "vilaro browser focus abcd1234",
  "vilaro browser close abcd1234",
  "vilaro browser screenshot",
  "vilaro browser screenshot --full-page",
  "vilaro browser screenshot --ref 12",
  "vilaro browser snapshot",
  "vilaro browser snapshot --format aria --limit 200",
  "vilaro browser snapshot --efficient",
  "vilaro browser snapshot --labels",
];

export const browserActionExamples = [
  "vilaro browser navigate https://example.com",
  "vilaro browser resize 1280 720",
  "vilaro browser click 12 --double",
  'vilaro browser type 23 "hello" --submit',
  "vilaro browser press Enter",
  "vilaro browser hover 44",
  "vilaro browser drag 10 11",
  "vilaro browser select 9 OptionA OptionB",
  "vilaro browser upload /tmp/vilaro/uploads/file.pdf",
  'vilaro browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "vilaro browser dialog --accept",
  'vilaro browser wait --text "Done"',
  "vilaro browser evaluate --fn '(el) => el.textContent' --ref 7",
  "vilaro browser console --level error",
  "vilaro browser pdf",
];
