export const browserCoreExamples = [
  "velaro browser status",
  "velaro browser start",
  "velaro browser stop",
  "velaro browser tabs",
  "velaro browser open https://example.com",
  "velaro browser focus abcd1234",
  "velaro browser close abcd1234",
  "velaro browser screenshot",
  "velaro browser screenshot --full-page",
  "velaro browser screenshot --ref 12",
  "velaro browser snapshot",
  "velaro browser snapshot --format aria --limit 200",
  "velaro browser snapshot --efficient",
  "velaro browser snapshot --labels",
];

export const browserActionExamples = [
  "velaro browser navigate https://example.com",
  "velaro browser resize 1280 720",
  "velaro browser click 12 --double",
  'vilaro browser type 23 "hello" --submit',
  "velaro browser press Enter",
  "velaro browser hover 44",
  "velaro browser drag 10 11",
  "velaro browser select 9 OptionA OptionB",
  "velaro browser upload /tmp/vilaro/uploads/file.pdf",
  'vilaro browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "velaro browser dialog --accept",
  'vilaro browser wait --text "Done"',
  "velaro browser evaluate --fn '(el) => el.textContent' --ref 7",
  "velaro browser console --level error",
  "velaro browser pdf",
];
